name: GitHub-Profile-Summary-Cards

on:
  schedule:
    - cron: "0 0 * * *"  # 1日1回（GitHubのcronはUTC基準）
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4

      - uses: vn7n24fzkq/github-profile-summary-cards@release
        env:
          GITHUB_TOKEN: ${{ secrets.SUMMARY_GITHUB_TOKEN }}
        with:
          USERNAME: ${{ github.repository_owner }}
          BRANCH_NAME: ${{ github.event.repository.default_branch }}
          UTC_OFFSET: 8
          EXCLUDE: ""
          AUTO_PUSH: true
